version: "0.2.2"

services:
    nekogpt:
        restart: always
        image: cocomine/nekogpt2:latest
        environment:
            # Please fill up following environment variables
            - BOT_NAME=NekoGPT
            - DISCORD_TOKEN=
            - SPEECH_KEY=
            - SPEECH_REGION=
            - CHATGPT_BASE_URL=default
            - OPENAI_API_KEY=
            - OPENAI_ASSISTANT_ID=
        networks:
            - nekogpt_net
        volumes:
            # Replace this with the path to the folder where you want to store the database.
            - /path/to/your/data/folder:/database
        depends_on:
            - redis

    redis:
        restart: always
        image: redis:latest
        networks:
            - nekogpt_net
        # command: redis-server --save 300 1 --appendonly yes --appendfilename "appendonly.aof"
        volumes:
            - ./database:/data

networks:
    nekogpt_net:
        driver: bridge